main/urls.py
from main.views import register, login_user, logout_user, edit_product, delete_product, add_product_entry_ajax, create_product_flutter
from django.urls import path
from main.views import show_main, create_product_entry, show_xml, show_json, show_xml_by_id, show_json_by_id

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product-entry', create_product_entry, name='create_product_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<str:id>', delete_product, name='delete_product'),
    path('create-product-entry-ajax', add_product_entry_ajax, name='create_product_entry_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

warunk_chill/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)  # Nama produk
    price = models.DecimalField(max_digits=10, decimal_places=2)  # Harga produk
    description = models.TextField()  # Deskripsi produk
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.name

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "quantity"]

    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)
        

main/views.py
import datetime
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.shortcuts import render, redirect, reverse
from main.forms import ProductForm
from main.models import Product
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags

# Create your views here.
@login_required(login_url='/login')
def show_main(request):

    context = {
        'app_name': 'warunk_chill',
        'name': request.user.username,
        'class_name': 'PBP - D',
        'last_login': request.COOKIES.get('last_login', 'Not available'),
    }
    return render(request, 'main.html', context)

@login_required(login_url='/login')
def create_product_entry(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product_entry = form.save(commit=False)
        product_entry.user = request.user
        product_entry.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_product_entry.html", context)

def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
        user = form.get_user()
        login(request, user)
        response = HttpResponseRedirect(reverse("main:show_main"))
        response.set_cookie('last_login', str(datetime.datetime.now()))
        return response
      else:
        messages.error(request, "Invalid username or password. Please try again.")

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/login')
def edit_product(request, id):
    # Get product entry berdasarkan id
    product = Product.objects.get(pk = id)

    # Set product entry sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

@login_required(login_url='/login')
def delete_product(request, id):
    # Get product berdasarkan id
    product = Product.objects.get(pk = id)
    # Hapus product
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_product_entry_ajax(request):
    name = strip_tags(request.POST.get("name"))
    price = request.POST.get("price")
    description = strip_tags(request.POST.get("description"))
    quantity = request.POST.get("quantity")

    user = request.user

    new_product = Product(
        name=name, 
        price=price,
        description=description,
        quantity=quantity,
        user=user
    )
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse
...
@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = Product.objects.create(
            user=request.user,
            name=data["name"],
            price=int(data["price"]),
            description=data["description"],
            quantity=int(data["quantity"]),
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product_entry.html
{% extends 'base.html' %}
{% block content %}

<div class="bg-gradient-to-b from-black via-[#121212] to-[#001F3F] min-h-screen">

  <!-- Navbar -->
  <div class="p-6">
    {% include 'navbar.html' %}
  </div>

  <h1 class="flex justify-center text-4xl font-sans mb-6 mt-12 text-white">Create Product Entry</h1>

  <div class=" flex justify-center mt-4 items-center">
    <div class="bg-gray-300 shadow-lg rounded-lg p-8 max-w-4xl w-full">

      <!-- Form Section -->
      <form method="POST" class="grid grid-cols-2 gap-6 w-full">
        {% csrf_token %}
        
        <!-- Left Column for product name, price, quantity, and submit button -->
        <div class="space-y-6">
          <!-- Product name Input -->
          <div>
            <label for="name" class="font-sans">Nama Produk</label>
            <input type="text" name="name" id="name" placeholder="Masukkan nama produk" 
              class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none font-sans text-gray-900"
              required>
          </div>

          <!-- Product price Input -->
          <div>
            <label for="price" class="font-sans">Harga Produk</label>
            <input type="number" name="price" id="price" placeholder="Masukkan harga produk" 
              class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none font-sans text-gray-900 appearance-none"
              min="1" oninput="this.value = Math.abs(this.value)" required>
          </div>

          <!-- Product quantity Input -->
          <div>
            <label for="quantity" class="font-sans">Jumlah Produk</label>
            <input type="number" name="quantity" id="quantity" placeholder="Masukkan jumlah produk" 
              class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none font-sans text-gray-900 appearance-none"
              min="1" oninput="this.value = Math.abs(this.value)" required>
          </div>

          <!-- Submit button -->
          <div class="mt-6">
            <input type="submit" value="Add Product Entry"
              class="w-full bg-slate-600 text-white p-3 rounded-lg font-semibold hover:bg-slate-800 focus:ring-4 focus:ring-blue-300 font-sans focus:outline-none">
          </div>
        </div>

        <!-- Right Column for product description -->
        <div class="flex flex-col justify-start">
          <!-- Product description Input -->
          <label for="description" class="font-sans">Deskripsi Produk</label>
          <textarea name="description" id="description" placeholder="Deskripsikan produk anda" 
            class="w-full h-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none font-sans text-gray-900"
            required></textarea>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="bg-gradient-to-b from-black via-[#121212] to-[#001F3F] min-h-screen">
      <!-- Navbar -->
    <div class="p-6">
        {% include 'navbar.html' %}
    </div>

    <h1 class="flex justify-center text-4xl font-sans mb-6 mt-12 text-white">Edit Product Entry</h1>

    <div class=" flex justify-center mt-4 items-center">
        <div class="bg-gray-300 shadow-lg rounded-lg p-8 max-w-4xl w-full">
            <!-- Form Section -->
            <form method="POST" class="grid grid-cols-2 gap-6 w-full">
                {% csrf_token %}
                
                <!-- Left Column for product name, price, quantity, and submit button -->
                <div class="space-y-6">
                <!-- Product name Input -->
                <div>
                    <label for="name" class="font-sans">Nama Produk</label>
                    <input type="text" name="name" id="name" placeholder="Masukkan nama produk"
                    value= "{{ product.name }}" 
                    class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none font-sans text-gray-900" 
                    required>
                </div>

                <!-- Product price Input -->
                <div>
                    <label for="price" class="font-sans">Harga Produk</label>
                    <input type="number" name="price" id="price" placeholder="Masukkan harga produk" 
                    class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none font-sans text-gray-900 appearance-none"
                    value="{{ product.price }}"
                    min="1" oninput="this.value = Math.abs(this.value)" required>
                </div>

                <!-- Product quantity Input -->
                <div>
                    <label for="quantity" class="font-sans">Jumlah Produk</label>
                    <input type="number" name="quantity" id="quantity" placeholder="Masukkan jumlah produk" 
                    class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none font-sans text-gray-900 appearance-none"
                    value="{{ product.quantity }}"
                    min="1" oninput="this.value = Math.abs(this.value)" required>
                </div>

                <!-- Submit button -->
                <div class="mt-6">
                    <input type="submit" value="Edit Product Entry"
                    class="w-full font-sans bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg transform hover:scale-105 transition duration-300 ease-in-out py-2 px-4 rounded">
                </div>
                </div>

                <!-- Right Column for product description -->
                <div class="flex flex-col justify-start">
                <!-- Product description Input -->
                <label for="description" class="font-sans">Deskripsi Produk</label>
                <textarea name="description" id="description" placeholder="Deskripsikan produk anda" 
                    class="w-full h-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none font-sans text-gray-900"
                    required>{{ product.description }}</textarea>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="bg-gradient-to-b from-black via-[#121212] to-[#001F3F] flex flex-col min-h-screen">
  <h1 class="flex justify-center text-7xl font-mono mt-24 text-white"> Warunk Chill </h1>
  <blockquote class="flex justify-center text-2xl font-mono italic text-white">{{ tagline }}</blockquote>
  <div class="flex justify-center mt-28 items-center">
    <div class="bg-gray-300 shadow-lg rounded-lg p-8 max-w-sm w-full">
      <h1 class="text-2xl font-bold mb-2 font-sans">Login</h1>
      <p class="text-sm mb-6 font-sans">Stay updated and never let a great deal slip away.</p>

      <form method="POST" action="" class="space-y-4">
        {% csrf_token %}
        
        <!-- Username Input -->
        <div>
          <label for="id_username" class="sr-only">Nama Akun</label>
          <input type="text" name="username" id="id_username" placeholder="Nama akun" 
            class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none font-sans text-gray-900"
            required>
        </div>

        <!-- Password Input -->
        <div class="relative">
          <label for="id_password" class="sr-only">Kata sandi</label>
          <input type="password" name="password" id="id_password" placeholder="Kata sandi" 
            class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none font-sans text-gray-900"
            required>
        </div>

        <!-- Login Button -->
        <div>
          <input type="submit" value="Login" 
            class="w-full bg-[#262626] text-white p-3 rounded-lg font-sans hover:bg-[#1b1b1b] transform hover:scale-105 transition duration-300 ease-in-out">
        </div>
      </form>
      
      <div class="text-center mt-4">
        <a href="{% url 'main:register' %}" class="font-sans hover:underline">Belum punya akun? Buat akun baru</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
<title>Warunk Chill</title>
{% endblock meta %}

{% block content %}

  <div class="bg-gradient-to-b from-black via-[#121212] to-[#292929] min-h-screen font-sans text-gray-200">

    <!-- Navbar -->
    <div class="p-6">
      {% include 'navbar.html' %}
    </div>

    <!-- Header -->
    <div class="py-8">
      <h1 class="text-4xl font-extrabold text-center font-mono text-white tracking-wide">Warunk Chill</h1>
      <h2 class="text-2xl font-semibold text-center font-mono text-white mt-2">{{ tagline }}</h2>
    </div>
    
    <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
      <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
        <!-- Modal header -->
        <div class="flex items-center justify-between p-4 border-b rounded-t">
          <h3 class="text-xl font-semibold text-gray-900">
            Add New Mood Entry
          </h3>
          <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
            <span class="sr-only">Close modal</span>
          </button>
        </div>

        <!-- Modal body -->
        <div class="px-6 py-4 space-y-6 form-style">
          <form id="productEntryForm">
            <div class="mb-4">
              <label for="name" class="block text-sm font-medium text-gray-700">Product Name</label>
              <input type="text" id="name" name="name" class="mt-1 block w-full border text-black border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Enter your product name" required>
            </div>
            <div class="mb-4">
              <label for="description" class="block text-sm font-medium text-gray-700">Product Description</label>
              <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border text-black border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Describe your product(s)" required></textarea>
            </div>
            <div class="mb-4">
              <label for="price" class="block text-sm font-medium text-gray-700">Price</label>
              <input type="number" id="price" name="price" min="1" class="mt-1 block w-full border text-black border-gray-300 rounded-md p-2 hover:border-indigo-700" required placeholder="Enter the product's price">
            </div>
            <div class="mb-4">
              <label for="quantity" class="block text-sm font-medium text-gray-700">Quantity</label>
              <input type="number" id="quantity" name="quantity" min="1" class="mt-1 block w-full border text-black border-gray-300 rounded-md p-2 hover:border-indigo-700" required placeholder="Enter the quantity">
            </div>
          </form>
        </div>
        <!-- Modal footer -->
        <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
          <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
          <button type="submit" id="submitProductEntry" form="productEntryForm" class="bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
        </div>
      </div>
    </div>

    <!-- Add New Product Button -->
    <div class="flex justify-end px-6 mt-8 gap-x-4">
      <a href="{% url 'main:create_product_entry' %}">
        <button class="btn bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105">
          Add New Product Entry
        </button>
      </a>
        <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105" onclick="showModal();">
        Add New Product Entry by AJAX
        </button>
    </div>
 
    <!-- Kontainer Card Produk -->
    <div id="product_entry_cards" class="flex flex-wrap gap-4 justify-center p-6"></div>
  </div>

  <script>
    // Fungsi untuk mengambil data produk dari backend
    async function getProductEntries(){
        return fetch("{% url 'main:show_json' %}").then((res) => res.json());
    }

    // Fungsi untuk me-refresh tampilan produk
    async function refreshProductEntries() {
      // Kosongkan konten sebelumnya
      const productContainer = document.getElementById("product_entry_cards");
      productContainer.innerHTML = "";

      // Ambil data produk
      const productEntries = await getProductEntries();
      let htmlString = "";

      // Jika tidak ada produk, tampilkan gambar "sedih-banget"
      if (productEntries.length === 0) {
        htmlString = `
          <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
            <img src="{% static 'image/sedih-banget.gif' %}" alt="Sad face" class="w-72 h-72"/>
            <p class="text-center text-gray-600 mt-4">Belum ada data produk pada sistem.</p>
          </div>
        `;
      } else {
        // Tampilkan data produk dalam bentuk card
        productEntries.forEach((item) => {
          const name = DOMPurify.sanitize(item.fields.name);
          const description = DOMPurify.sanitize(item.fields.description);
      
          htmlString += `
            <div class="bg-gray-300 rounded-lg p-3 min-w-[250px] max-w-md m-4">
              <h2 class="text-gray-700 font-bold text-xl mb-2">${item.fields.name}</h2>
              <p class="text-gray-700 mb-4">${item.fields.description}</p>
              <p class="text-gray-600 font-semibold">Price: Rp ${item.fields.price}</p>
              <p class="text-gray-600">Quantity: ${item.fields.quantity}</p>

              <!-- Tombol Edit dan Hapus -->
              <div class="flex justify-end space-x-2 mt-4">
                <a href="/edit/${item.pk}" class="bg-yellow-500 hover:bg-yellow-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                  </svg>
                </a>
                <a href="/delete/${item.pk}" class="bg-red-500 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                  </svg>
                </a>
              </div>
            </div>
          `;
        });
      }

      // Masukkan HTML produk ke dalam kontainer
      productContainer.innerHTML = htmlString;
    }
    
    function addProductEntry() {
      fetch("{% url 'main:create_product_entry_ajax' %}", {
        method: "POST",
        body: new FormData(document.querySelector('#productEntryForm')),
      })
      .then(response => refreshProductEntries())
      
      document.getElementById("productEntryForm").reset(); 
      document.querySelector("[data-modal-toggle='crudModal']").click();
      
      return false;
    }
    
    document.getElementById("productEntryForm").addEventListener("submit", (e) => {
    e.preventDefault();
    addProductEntry();
    })
    
    // Panggil fungsi refresh setelah halaman dimuat
    refreshProductEntries();

    // Tambahkan event listener untuk tombol "Add New Product Entry"
    const modal = document.getElementById('crudModal');
    const modalContent = document.getElementById('crudModalContent');

    function showModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modal.classList.remove('hidden'); 
        setTimeout(() => {
          modalContent.classList.remove('opacity-0', 'scale-95');
          modalContent.classList.add('opacity-100', 'scale-100');
        }, 50); 
    }

    function hideModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modalContent.classList.remove('opacity-100', 'scale-100');
        modalContent.classList.add('opacity-0', 'scale-95');

        setTimeout(() => {
          modal.classList.add('hidden');
        }, 150); 
    }

    document.getElementById("cancelButton").addEventListener("click", hideModal);
    document.getElementById("closeModalBtn").addEventListener("click", hideModal);

  </script>
{% endblock content %}

main/templates/product_card.html
<div class="bg-gray-300 rounded-lg p-6 max-w-xs m-4">
    <h2 class="text-gray-700 font-bold text-xl mb-2">{{ product_entry.name }}</h2>
    <p class="text-gray-700 mb-4">{{ product_entry.description }}</p>
    <p class="text-gray-600 font-semibold">Price: Rp {{ product_entry.price }}</p>
    <p class="text-gray-600">Quantity: {{ product_entry.quantity }}</p>
    
    <div class="mt-4 flex justify-start">
      <!-- Edit button -->
      <a href="{% url 'main:edit_product' product_entry.pk %}" class="bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg transform hover:scale-105 transition duration-300 ease-in-out py-2 px-4 rounded">
        Edit
      </a> 
      
      <!-- Delete button with margin left -->
      <a href="{% url 'main:delete_product' product_entry.pk %}" class="text-white bg-red-500 hover:bg-red-600 hover:scale-105 transition duration-300 ease-in-out py-2 px-4 ml-10 rounded">
        Delete
      </a>
    </div>
    
  </div>
  

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}

<div class="bg-gradient-to-b from-black via-[#121212] to-[#001F3F] flex flex-col min-h-screen">
  <div class="flex justify-center mt-28 items-center">
    <div class="bg-gray-200 shadow-lg rounded-lg p-8 max-w-sm w-full">
      <h1 class="text-2xl font-bold text-gray-800 mb-2 font-sans">Register</h1>
      <p class="text-sm text-gray-600 mb-6 font-sans">Just one step, discover ahead</p>
      
      <form method="POST" class="">
        {% csrf_token %}
        <div class="relative mt-4">
            <label for="id_username" class="font-mono text-xs">Nama Akun</label>
            <input type="text" name="username" id="id_username" placeholder="Masukkan nama akun Anda" required
            class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none font-sans text-gray-900">
        </div>
    
        <div class="relative mt-4">
            <label for="id_password" class="font-mono text-xs">Kata sandi</label>
            <input type="password" name="password1" id="id_password" placeholder="Masukkan sandi yang aman" required
            class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none font-sans text-gray-900">
        </div>
    
        <div class="relative mt-4">
            <label for="id_password2" class="font-mono text-xs">Konfirmasi Kata sandi</label>
            <input type="password" name="password2" id="id_password2" placeholder="Konfirmasi sandi" required
            class="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none font-sans text-gray-900">
        </div>
    
        <div class="relative mt-24">
            <input type="submit" name="submit" value="Daftar"
            class="w-full bg-[#262626] text-white p-3 rounded-lg font-sans hover:bg-[#1b1b1b]">
        </div>
      </form>    
    
      <!-- Back Button -->
      <div class="relative mt-3">
        <a href="{% url 'main:login' %}" 
          class="w-full bg-[#262626] text-white p-3 rounded-lg font-sans hover:bg-[#1b1b1b] text-center block">
            Back
        </a>
      </div>
    </div>

    <div class="bg-gray-200 shadow-lg rounded-lg p-8 max-w-sm w-full">
      <div class="font-sans whitespace-pre-line">
        Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.

        Password:	
        Your password can’t be too similar to your other personal information.
        Your password must contain at least 8 characters.
        Your password can’t be a commonly used password.
        Your password can’t be entirely numeric.

        Password confirmation:	
        Enter the same password as before, for verification.
      </div>
    </div>
    
    <!-- Menampilkan pesan jika ada -->
    {% if messages %}
      <ul>
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
</div>

{% endblock content %}